### ISSUE TITLE
Missing `IFixerClient` in Console apps with DI

### ISSUE THREAD

**Issue by Meligy** [purkayasta/Fixerr#6]
Hello,

First, let me say thanks heaps for this library. There's a lot of thought and effort gone into it, and this issue does not contradict with this fact.

Now, a small issue or feature request, depending on how you see it.

Let's say you configure the client like this:

```csharp
var host = Host.CreateDefaultBuilder(args)
    .ConfigureHostConfiguration(configHost =>
    {
        configHost.AddUserSecrets<Program>();
    })
    .ConfigureServices((hostContext, services) =>
    {
        // dotnet user-secrets set "FixerApiKey" "your_api_key_here"
        const string keyName = "FixerApiKey";
        var apiKey = hostContext.Configuration[keyName];
        ArgumentException.ThrowIfNullOrEmpty(apiKey, keyName);        
        // Now setup fixerClient
        services.AddFixer(apiKey, isPaidSubscription:true);
    })
    .Build();
```

I did this because when I think `HttpClient`, I think hosting and configuration. Also the idea of storing the API key in user secret sounded nice.

But then you try to use it like this:

```csharp
// Get the fixerClient from the service provider
using var scope = host.Services.CreateScope();
var fixerClient = scope.ServiceProvider.GetService<IFixerClient>();
```

But you get an error because there's no `IFixerClient` in DI.

You think you can workaround it by adding the following to `.ConfigureServices(...)`:
```chsarp
services.AddTransient<IFixerClient, FixerClient>();
```

But `FixerClient` is actually internal, your only way is to do something like this, also in `.ConfigureServices(...)`:

```csharp
services.AddTransient<IFixerClient>(provider =>
{
    var httpFactory = provider.GetRequiredService<HttpClient>();
    var options = provider.GetRequiredService<IOptions<FixerOptions>>().Value;
    var client = FixerFactory.CreateFixerClient(httpFactory, options.ApiKey, options.IsPaidSubscription);
    return client;
});
```

But this looks like something that you'd expect `AddFixer` to do, no?

**Comment by purkayasta** [comment]
Thank you so much for reporting this bug @Meligy. The fix is coming up.

**Comment by purkayasta** [comment]
@Meligy released a new version with some fixes. Can you check again and confirm, please?

**Comment by Meligy** [comment]
Hello again,

Thanks a lot for the very fast response. That seems to work, which is awesome.

However, I noticed that this breaks semantic versioning. Changing the namespace to `Fixerr.Installer` should be a breaking changing, so, the new version should be 2.x.x not 1.3.x.

Not a big deal for me, and happy to close this issue (thanks again). I just thought you might be interested in this comment.

**Comment by Meligy** [comment]
Also, looking at the code, `FixerEnvironment` seems like a step backwards if you allow me to say so.
Earlier you could in theory have 2 different clients with 2 different API keys, etc.

But again, this does not affect me, just geeking out!

**Comment by purkayasta** [comment]
@Meligy you are absolutely right about the versioning. I should have changed it to a new version number, not a sub-version number. I released a bug-free version as quickly as possible.

Returning to the ```FixerEnvironment``` class, it was there before, IOptions was there to give more options to the user setup even more but internally I have used this static class FixerEnvironment for the key setup. I have removed the Options pattern for now to release this. But I will bring the options patterns in the next iteration.

Btw you can still use 2 different API keys if you want. One is through the configuration and another one is through passing with the method itself.

And thank you 🙏 so much for the bug report @Meligy.
